# SPDX-FileCopyrightText: 2022 Stephan Lachnit <stephanlachnit@debian.org>
# SPDX-License-Identifier: CC0-1.0

name: Build and test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dist:
    name: Build wheel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: python3 -m pip install build urwid
      - name: Build
        run: make build
  docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Sphinx
        run: python3 -m pip install urwid myst-parser sphinx sphinx_rtd_theme sphinxcontrib.apidoc
      - name: Build documentation
        run: make docs
  pytest:
    name: Unit tests
    strategy:
      matrix:
        python-version: ["3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pytest
        run: python3 -m pip install pytest
      - name: Pytest (Python ${{ matrix.python-version }})
        run: make pytest
